#include "ResourcesLoader.h"

ResourcesLoader::ResourcesLoader(SdlRenderer& renderer):
  tx_objects(renderer, "../resources/textures/objects.png", 152, 0, 136),
  tx_rocket(renderer, "../resources/textures/rocket.png"),
  tx_explosion(renderer, "../resources/textures/explosion_strip9.png"),
  tx_bullethit(renderer, "../resources/textures/bullethit_strip9.png"),
  tx_walls(renderer, "../resources/textures/walls.png"),
  tx_guardDogDown(renderer, "../resources/textures/enemies/guardDog/down_strip5.png", 152, 0, 136),
  tx_guardDogDownLeft(renderer, "../resources/textures/enemies/guardDog/downleft_strip5.png", 152, 0, 136),
  tx_guardDogLeft(renderer, "../resources/textures/enemies/guardDog/left_strip5.png", 152, 0, 136),
  tx_guardDogUpLeft(renderer, "../resources/textures/enemies/guardDog/upleft_strip5.png", 152, 0, 136),
  tx_guardDogUp(renderer, "../resources/textures/enemies/guardDog/up_strip5.png", 152, 0, 136),
  tx_guardDogShooting(renderer, "../resources/textures/enemies/guardDog/shooting_strip3.png", 152, 0, 136),
  tx_guardDogDying(renderer, "../resources/textures/enemies/guardDog/dying_strip5.png", 152, 0, 136),
  tx_guardDown(renderer, "../resources/textures/enemies/guard/down_strip5.png", 152, 0, 136),
  tx_guardDownLeft(renderer, "../resources/textures/enemies/guard/downleft_strip5.png", 152, 0, 136),
  tx_guardLeft(renderer, "../resources/textures/enemies/guard/left_strip5.png", 152, 0, 136),
  tx_guardUpLeft(renderer, "../resources/textures/enemies/guard/upleft_strip5.png", 152, 0, 136),
  tx_guardUp(renderer, "../resources/textures/enemies/guard/up_strip5.png", 152, 0, 136),
  tx_guardShooting(renderer, "../resources/textures/enemies/guard/shooting_strip3.png", 152, 0, 136),
  tx_guardDying(renderer, "../resources/textures/enemies/guard/dying_strip5.png", 152, 0, 136),
  tx_ssDown(renderer, "../resources/textures/enemies/ss/down_strip5.png"),
  tx_ssDownLeft(renderer, "../resources/textures/enemies/ss/downleft_strip5.png"),
  tx_ssLeft(renderer, "../resources/textures/enemies/ss/left_strip5.png"),
  tx_ssUpLeft(renderer, "../resources/textures/enemies/ss/upleft_strip5.png"),
  tx_ssUp(renderer, "../resources/textures/enemies/ss/up_strip5.png"),
  tx_ssShooting(renderer, "../resources/textures/enemies/ss/shooting_strip3.png"),
  tx_ssDying(renderer, "../resources/textures/enemies/ss/dying_strip5.png"),
  tx_officerDown(renderer, "../resources/textures/enemies/officer/down_strip5.png", 152, 0, 136),
  tx_officerDownLeft(renderer, "../resources/textures/enemies/officer/downleft_strip5.png", 152, 0, 136),
  tx_officerLeft(renderer, "../resources/textures/enemies/officer/left_strip5.png", 152, 0, 136),
  tx_officerUpLeft(renderer, "../resources/textures/enemies/officer/upleft_strip5.png", 152, 0, 136),
  tx_officerUp(renderer, "../resources/textures/enemies/officer/up_strip5.png", 152, 0, 136),
  tx_officerShooting(renderer, "../resources/textures/enemies/officer/shooting_strip3.png", 152, 0, 136),
  tx_officerDying(renderer, "../resources/textures/enemies/officer/dying_strip5.png", 152, 0, 136),
  tx_mutantDown(renderer, "../resources/textures/enemies/mutant/down_strip5.png", 0, 0, 128),
  tx_mutantDownLeft(renderer, "../resources/textures/enemies/mutant/downleft_strip5.png", 0, 0, 128),
  tx_mutantLeft(renderer, "../resources/textures/enemies/mutant/left_strip5.png", 0, 0, 128),
  tx_mutantUpLeft(renderer, "../resources/textures/enemies/mutant/upleft_strip5.png", 0, 0, 128),
  tx_mutantUp(renderer, "../resources/textures/enemies/mutant/up_strip5.png", 0, 0, 128),
  tx_mutantShooting(renderer, "../resources/textures/enemies/mutant/shooting_strip3.png", 0, 0, 128),
  tx_mutantDying(renderer, "../resources/textures/enemies/mutant/dying_strip5.png", 0, 0, 128),

  // Sonidos
  snd_cuchillo("../resources/sounds/cuchillo.mp3"),
  snd_pistola1("../resources/sounds/pistola1.mp3"),
  snd_pistola2("../resources/sounds/pistola2.mp3"),
  snd_ametralladora1("../resources/sounds/ametralladora1.mp3"),
  snd_ametralladora2("../resources/sounds/ametralladora2.mp3"),
  snd_canionDeCadena("../resources/sounds/canionDeCadena.mp3"),
  snd_lanzacohetes("../resources/sounds/rocket.mp3"),
  snd_dying("../resources/sounds/dying.mp3"),
  snd_explosion("../resources/sounds/explosion.mp3"),
  snd_bullethit("../resources/sounds/bullethit.mp3"),
  snd_door_open("../resources/sounds/door_open.mp3"),
  snd_door_closed("../resources/sounds/door_closed.mp3") {}
ResourcesLoader::~ResourcesLoader() {}
