#include "../common_src/pathsAssets.h"
#include "ResourcesLoader.h"

ResourcesLoader::ResourcesLoader(SdlRenderer& renderer):
  tx_objects(renderer, OBJECTS_TEXTURE_PATH, 152, 0, 136),
  tx_rocket(renderer, ROCKET_PATH),
  tx_explosion(renderer, EXPLOSION_PATH),
  tx_bullethit(renderer, BULLET_HIT_PATH),
  tx_walls(renderer, WALLS_TEXTURE_PATH),
  tx_guardDogDown(renderer, GUARD_DOG_DOWN, 152, 0, 136),
  tx_guardDogDownLeft(renderer, GUARD_DOG_DOWN_LEFT, 152, 0, 136),
  tx_guardDogLeft(renderer, GUARD_DOG_LEFT, 152, 0, 136),
  tx_guardDogUpLeft(renderer, GUARD_DOG_UP_LEFT, 152, 0, 136),
  tx_guardDogUp(renderer, GUARD_DOG_UP, 152, 0, 136),
  tx_guardDogShooting(renderer, GUARD_DOG_SHOOTING, 152, 0, 136),
  tx_guardDogDying(renderer, GUARD_DOG_DYING, 152, 0, 136),
  tx_guardDown(renderer, GUARD_DOWN, 152, 0, 136),
  tx_guardDownLeft(renderer, GUARD_DOWN_LEFT", 152, 0, 136),
  tx_guardLeft(renderer, GUARD_LEFT, 152, 0, 136),
  tx_guardUpLeft(renderer, GUARD_UP_LEFT, 152, 0, 136),
  tx_guardUp(renderer, GUARD_UP, 152, 0, 136),
  tx_guardShooting(renderer, GUARD_SHOOTING, 152, 0, 136),
  tx_guardDying(renderer, GUARD_DYING, 152, 0, 136),
  tx_ssDown(renderer, SS_DOWN),
  tx_ssDownLeft(renderer, SS_DOWN_LEFT),
  tx_ssLeft(renderer, SS_LEFT),
  tx_ssUpLeft(renderer, SS_UP_LEFT),
  tx_ssUp(renderer, SS_UP),
  tx_ssShooting(renderer, SS_SHOOTING),
  tx_ssDying(renderer, SS_DYING),
  tx_officerDown(renderer, OFFICER_DOWN, 152, 0, 136),
  tx_officerDownLeft(renderer, OFFICER_DOWN_LEFT, 152, 0, 136),
  tx_officerLeft(renderer, OFFICER_LEFT, 152, 0, 136),
  tx_officerUpLeft(renderer, OFFICER_UP_LEFT, 152, 0, 136),
  tx_officerUp(renderer, OFFICER_UP, 152, 0, 136),
  tx_officerShooting(renderer, OFFICER_SHOOTING, 152, 0, 136),
  tx_officerDying(renderer, OFFICER_DYING, 152, 0, 136),
  tx_mutantDown(renderer, MUTANT_DOWN, 0, 0, 128),
  tx_mutantDownLeft(renderer, MUTANT_DOWN_LEFT, 0, 0, 128),
  tx_mutantLeft(renderer, MUTANT_LEFT, 0, 0, 128),
  tx_mutantUpLeft(renderer, MUTANT_UP_LEFT, 0, 0, 128),
  tx_mutantUp(renderer, MUTANT_UP, 0, 0, 128),
  tx_mutantShooting(renderer, MUTANT_SHOOTING, 0, 0, 128),
  tx_mutantDying(renderer, MUTANT_DYING, 0, 0, 128),

  // Sonidos
  snd_cuchillo(SND_CUCHILLO_PATH),
  snd_pistola1(SND_PISTOLA_PATH),
  snd_pistola2(SND_PISTOLA2_PATH),
  snd_ametralladora1(SND_AMETRALLADORA1_PATH),
  snd_ametralladora2(SND_AMETRALLADORA2_PATH),
  snd_canionDeCadena(SND_CANIONDECADENA_PATH),
  snd_lanzacohetes(SND_LANZACOHETES_PATH),
  snd_dying(SND_DYING_PATH),
  snd_explosion(SND_EXPLOSION_PATH),
  snd_bullethit(SND_BULLETHIT_PATH),
  snd_door_open(SND_DOOR_OPEN_PATH),
  snd_door_closed(SND_DOOR_CLOSE_PATH) {}
ResourcesLoader::~ResourcesLoader() {}
