gun:
  max_damage: 10
  max_spread: 20
  ammo_cost: 1
  cooldown: 300
  stability_reset: 200
  max_acurate_range: 10

knife:
  max_damage: 10
  max_spread: 10
  ammo_cost: 10
  cooldown: 300
  stability_reset: 10
  max_acurate_range: 10

machine gun:
  max_damage: 10
  max_spread: 40
  ammo_cost: 1
  cooldown: 100
  stability_reset: 200
  max_acurate_range: 10

minigun:
  max_damage: 10
  max_spread: 70
  ammo_cost: 1
  cooldown: 100
  stability_reset: 100
  max_acurate_range: 100

rocket launcher:
  max_damage: 100
  max_spread: 0
  ammo_cost: 8
  cooldown: 500
  stability_reset: 100
  max_acurate_range: 100

player:
  health: 100 
  lives: 2
  hitbox_radius: 0.2
  linear_vel: 0.2
  angular_vel: 5
